// The generated design fixtures (db/seeds/payments.ts) against the ORIGINAL bundle's own state.txs, event by event, and the
// original's calc() outputs against calcInvoice. The original numbers invoices by a countdown that collides with the explicit
// ids, so rows are compared by position (same construction order); the renumbering is checked separately.
import { describe, expect, it } from 'vitest'
import { calcInvoice } from '../../src/modules/payments/calc.js'
import { designInvoices } from '../../db/seeds/payments.js'
import { cents, oracleCalcs, oracleFixtures, STATUS_KEY } from './golden.js'

const mine = designInvoices()
const orig = oracleFixtures()

describe('design fixtures vs the original bundle', () => {
  it('105 invoices: 16 explicit and 89 generated by mulberry32(987654)', () => {
    expect(orig).toHaveLength(105)
    expect(mine).toHaveLength(105)
  })

  it('every invoice matches the original field by field, in the same order (this proves the RNG call order)', () => {
    for (const [i, o] of orig.entries()) {
      const m = mine[i]!
      const where = `invoice #${i} (${o.id})`
      expect(m.designId, where).toBe(o.id)
      expect([m.off, m.time, m.client, m.vehicle, m.staff, m.canceled], where).toEqual([
        o.off,
        o.time,
        o.client,
        o.vehicle,
        o.staff,
        o.canceled,
      ])
      expect(m.tipCents, where).toBe(cents(o.tip))
      expect(m.items, where).toEqual(o.items.map((x) => ({ name: x.name, priceCents: cents(x.price) })))
      expect(m.events.length, where).toBe(o.events.length)
      for (const [j, e] of o.events.entries()) {
        const me = m.events[j]!
        expect(me.type, `${where} event ${j}`).toBe(e.type)
        expect(me.amountCents, `${where} event ${j} amount`).toBe(cents(e.amt))
        expect(me.method ?? null, `${where} event ${j} method`).toBe(e.method ?? null)
        expect(me.dest ?? null, `${where} event ${j} dest`).toBe(e.dest ?? null)
        expect(me.status ?? null, `${where} event ${j} status`).toBe(e.status ?? null)
        expect(me.reason ?? null, `${where} event ${j} reason`).toBe(e.reason ?? null)
        expect(me.note ?? null, `${where} event ${j} note`).toBe(e.note ?? null)
        expect(me.by, `${where} event ${j} by`).toBe(e.by)
        expect(me.byRole ?? null, `${where} event ${j} byRole`).toBe(e.byRole ?? null)
        expect(me.expiry ?? null, `${where} event ${j} expiry`).toBe(e.expiry ?? null)
        expect(me.deposit ?? false, `${where} event ${j} deposit`).toBe(e.deposit ?? false)
        expect(me.t, `${where} event ${j} t`).toBe(e.t ?? '')
      }
    }
  })

  it('the explicit invoices keep their ids; generated ones are renumbered downward from 20608 skipping used ids', () => {
    const nos = mine.map((m) => m.no)
    expect(new Set(nos).size).toBe(105)
    expect(Math.max(...nos)).toBe(20610)
    expect(Math.min(...nos)).toBe(20506)
    const explicit = mine.slice(0, 16)
    expect(explicit.map((m) => m.no)).toEqual(explicit.map((m) => Number(m.designId.slice(4))))
    const generated = mine.slice(16).map((m) => m.no)
    expect(generated.slice(0, 4)).toEqual([20600, 20599, 20598, 20597])
    expect([...generated].sort((a, b) => b - a)).toEqual(generated)
    const used = new Set(explicit.map((m) => m.no))
    expect(generated.every((n) => !used.has(n))).toBe(true)
  })

  it('calcInvoice equals the original calc() for every invoice (cents vs the design floats)', () => {
    const calcs = oracleCalcs()
    for (const [i, m] of mine.entries()) {
      const o = calcs[i]!
      const c = calcInvoice({
        itemPrices: m.items.map((x) => x.priceCents),
        events: m.events.map((e) => ({
          type: e.type,
          amountCents: e.amountCents,
          status: e.type === 'refund' ? (e.status ?? 'done') : undefined,
          dest: e.type === 'refund' ? (e.dest ?? 'card') : undefined,
        })),
        taxBp: 700,
        tipCents: m.tipCents,
        canceled: m.canceled,
      })
      const where = `${m.designId} #${i}`
      expect(
        {
          items: c.items,
          adj: c.adj,
          sub: c.sub,
          tax: c.tax,
          total: c.total,
          paid: c.paid,
          paidOrig: c.paidOrig,
          creditApplied: c.creditApplied,
          refunded: c.refunded,
          balance: c.balance,
          refundable: c.refundable,
          toOrigMax: c.toOrigMax,
          issued: c.issued,
          net: c.net,
        },
        where,
      ).toEqual({
        items: cents(o.items),
        adj: cents(o.adj),
        sub: cents(o.sub),
        tax: cents(o.tax),
        total: cents(o.total),
        paid: cents(o.paid),
        paidOrig: cents(o.paidOrig),
        creditApplied: cents(o.creditApplied),
        refunded: cents(o.refunded),
        balance: cents(o.balance),
        refundable: cents(o.refundable),
        toOrigMax: cents(o.toOrigMax),
        issued: cents(o.issued),
        net: cents(o.net),
      })
      expect(c.pendingAmt, where).toBe(cents(o.pending.reduce((a, b) => a + b, 0)))
      expect(c.status, where).toBe(STATUS_KEY[o.status])
    }
  })
})
