-- Generated by pnpm db:schema (migrations applied to an empty schema, pg_dump --schema-only). Do not edit; add a migration.
--
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

--
-- Name: app_now(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.app_now() RETURNS timestamp with time zone
    LANGUAGE sql
    AS $$ select coalesce(nullif(current_setting('oasis.now', true), '')::timestamptz, clock_timestamp()) $$;

--
-- Name: audit_log_immutable(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.audit_log_immutable() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  raise exception 'audit_log is insert-only (% rejected)', tg_op using errcode = 'restrict_violation';
end
$$;

--
-- Name: ensure_location(uuid, text, text, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.ensure_location(p_id uuid, p_slug text, p_name text, p_timezone text DEFAULT 'America/New_York'::text) RETURNS uuid
    LANGUAGE plpgsql
    AS $$
declare
  v_id uuid;
begin
  insert into locations (id, slug, name, timezone) values (p_id, p_slug, p_name, p_timezone)
  on conflict (slug) do nothing;
  select id into v_id from locations where slug = p_slug;
  return v_id;
end
$$;

--
-- Name: realtime_channel_name(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.realtime_channel_name() RETURNS text
    LANGUAGE sql STABLE
    AS $$ select 'oasis_rt' || case when current_schema() = 'public' then '' else '_' || current_schema() end $$;

--
-- Name: realtime_events_notify(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.realtime_events_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  perform pg_notify(
    realtime_channel_name(),
    json_build_object('id', new.id, 'l', new.location_id, 'c', new.channel)::text
  );
  return null;
end
$$;

--
-- Name: realtime_purge(timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.realtime_purge(p_before timestamp with time zone) RETURNS bigint
    LANGUAGE plpgsql
    AS $$
declare
  v_max bigint;
  v_count bigint;
begin
  with d as (delete from realtime_events where at < p_before returning id)
  select max(id), count(*) into v_max, v_count from d;
  if v_max is not null then
    insert into realtime_state (id, purged_through) values (true, v_max)
    on conflict (id) do update set purged_through = greatest(realtime_state.purged_through, excluded.purged_through);
  end if;
  return v_count;
end
$$;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    at timestamp with time zone DEFAULT public.app_now() NOT NULL,
    location_id uuid NOT NULL,
    actor_user_id uuid,
    actor_employee_id uuid,
    actor_name text,
    actor_roles text,
    view_as_role_id uuid,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text,
    before jsonb,
    after jsonb,
    request_id text,
    idempotency_key text,
    ip inet
);

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;

--
-- Name: idempotency_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idempotency_keys (
    key text NOT NULL,
    actor text NOT NULL,
    method text NOT NULL,
    route text NOT NULL,
    request_hash text NOT NULL,
    state text NOT NULL,
    response_status smallint,
    response_body jsonb,
    response_headers jsonb,
    created_at timestamp with time zone DEFAULT public.app_now() NOT NULL,
    lock_expires_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT idempotency_keys_state_check CHECK ((state = ANY (ARRAY['in_flight'::text, 'done'::text])))
);

--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    timezone text DEFAULT 'America/New_York'::text NOT NULL,
    address text,
    lat numeric(9,6),
    lng numeric(9,6),
    created_at timestamp with time zone DEFAULT public.app_now() NOT NULL,
    CONSTRAINT locations_check CHECK (((btrim(name) <> ''::text) AND (btrim(timezone) <> ''::text))),
    CONSTRAINT locations_lat_check CHECK (((lat >= ('-90'::integer)::numeric) AND (lat <= (90)::numeric))),
    CONSTRAINT locations_lng_check CHECK (((lng >= ('-180'::integer)::numeric) AND (lng <= (180)::numeric)))
);

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid NOT NULL,
    location_id uuid NOT NULL,
    employee_id uuid,
    role_target text,
    kind text NOT NULL,
    title text NOT NULL,
    body text,
    entity_type text,
    entity_id text,
    created_at timestamp with time zone DEFAULT public.app_now() NOT NULL,
    read_at timestamp with time zone,
    CONSTRAINT notifications_check CHECK (((employee_id IS NULL) OR (role_target IS NULL)))
);

--
-- Name: realtime_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realtime_events (
    id bigint NOT NULL,
    at timestamp with time zone DEFAULT public.app_now() NOT NULL,
    location_id uuid NOT NULL,
    channel text NOT NULL,
    type text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    target_user_id uuid
);

--
-- Name: realtime_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.realtime_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: realtime_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.realtime_events_id_seq OWNED BY public.realtime_events.id;

--
-- Name: realtime_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realtime_state (
    id boolean DEFAULT true NOT NULL,
    purged_through bigint DEFAULT 0 NOT NULL,
    CONSTRAINT realtime_state_id_check CHECK (id)
);

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    name text NOT NULL,
    checksum text NOT NULL,
    applied_at timestamp with time zone NOT NULL
);

--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    location_id uuid NOT NULL,
    key text NOT NULL,
    value jsonb NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT public.app_now() NOT NULL
);

--
-- Name: webhook_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_log (
    id uuid NOT NULL,
    provider text NOT NULL,
    external_id text NOT NULL,
    headers jsonb DEFAULT '{}'::jsonb NOT NULL,
    body text,
    signature_valid boolean NOT NULL,
    received_at timestamp with time zone DEFAULT public.app_now() NOT NULL,
    processed_at timestamp with time zone,
    status text DEFAULT 'received'::text NOT NULL,
    error text,
    CONSTRAINT webhook_log_provider_check CHECK ((provider = ANY (ARRAY['squarespace'::text, 'smsgate'::text, 'ses'::text]))),
    CONSTRAINT webhook_log_status_check CHECK ((status = ANY (ARRAY['received'::text, 'processed'::text, 'ignored'::text, 'failed'::text])))
);

--
-- Name: audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);

--
-- Name: realtime_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realtime_events ALTER COLUMN id SET DEFAULT nextval('public.realtime_events_id_seq'::regclass);

--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

--
-- Name: idempotency_keys idempotency_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (key, actor);

--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);

--
-- Name: locations locations_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_slug_key UNIQUE (slug);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

--
-- Name: realtime_events realtime_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realtime_events
    ADD CONSTRAINT realtime_events_pkey PRIMARY KEY (id);

--
-- Name: realtime_state realtime_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realtime_state
    ADD CONSTRAINT realtime_state_pkey PRIMARY KEY (id);

--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (name);

--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (location_id, key);

--
-- Name: webhook_log webhook_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_log
    ADD CONSTRAINT webhook_log_pkey PRIMARY KEY (id);

--
-- Name: webhook_log webhook_log_provider_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_log
    ADD CONSTRAINT webhook_log_provider_external_id_key UNIQUE (provider, external_id);

--
-- Name: audit_log_actor_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_actor_idx ON public.audit_log USING btree (actor_user_id, id DESC);

--
-- Name: audit_log_entity_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_entity_idx ON public.audit_log USING btree (entity_type, entity_id, id DESC);

--
-- Name: audit_log_location_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_location_at_idx ON public.audit_log USING btree (location_id, at DESC);

--
-- Name: idempotency_keys_expires_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idempotency_keys_expires_idx ON public.idempotency_keys USING btree (expires_at);

--
-- Name: notifications_location_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_location_idx ON public.notifications USING btree (location_id, created_at DESC);

--
-- Name: notifications_unread_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_unread_idx ON public.notifications USING btree (employee_id) WHERE (read_at IS NULL);

--
-- Name: realtime_events_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realtime_events_at_idx ON public.realtime_events USING btree (at);

--
-- Name: realtime_events_location_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realtime_events_location_idx ON public.realtime_events USING btree (location_id, id);

--
-- Name: webhook_log_received_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX webhook_log_received_idx ON public.webhook_log USING btree (received_at);

--
-- Name: audit_log audit_log_no_update_delete; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_log_no_update_delete BEFORE DELETE OR UPDATE ON public.audit_log FOR EACH ROW EXECUTE FUNCTION public.audit_log_immutable();

--
-- Name: realtime_events realtime_events_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER realtime_events_notify AFTER INSERT ON public.realtime_events FOR EACH ROW EXECUTE FUNCTION public.realtime_events_notify();

--
-- Name: audit_log audit_log_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);

--
-- Name: notifications notifications_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE;

--
-- Name: realtime_events realtime_events_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realtime_events
    ADD CONSTRAINT realtime_events_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE;

--
-- Name: settings settings_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE;

--
--

