// pnpm db:schema [--check]
// Applies every migration to a throwaway schema of the DATABASE_URL server, dumps it with pg_dump --schema-only and
// writes db/schema.sql with the throwaway schema renamed to public, so the snapshot depends only on the migration
// files, never on what a developer database happens to contain. With --check it compares instead of writing.
// pg_dump comes from the postgresql15 package (dnf install postgresql15); its major version must match the server.
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { sql } from 'kysely'
import { createClock } from '../src/platform/clock.js'
import { createDb } from '../src/platform/db.js'
import { migrateUp } from '../src/platform/migrate.js'

if (existsSync('.env')) process.loadEnvFile('.env')
const check = process.argv.includes('--check')
const raw = process.env.DATABASE_URL
if (!raw) throw new Error('DATABASE_URL is not set')
// per-checkout name so two worktrees dumping against the same server never collide
const SCRATCH = `schema_dump_${createHash('sha1').update(process.cwd()).digest('hex').slice(0, 8)}`
const file = path.resolve('db/schema.sql')

async function dump(): Promise<string> {
  const url = new URL(raw!)
  const admin = createDb({ url: raw!, poolMax: 1 })
  try {
    await sql`drop schema if exists ${sql.id(SCRATCH)} cascade`.execute(admin)
    await migrateUp({ url: raw! }, { schema: SCRATCH, clock: createClock('2026-01-01T00:00:00Z') })
    const res = spawnSync(
      'pg_dump',
      [
        '--schema-only',
        '--no-owner',
        '--no-privileges',
        '--no-comments',
        `--schema=${SCRATCH}`,
        '-h',
        url.hostname,
        '-p',
        url.port || '5432',
        '-U',
        decodeURIComponent(url.username),
        url.pathname.slice(1),
      ],
      {
        env: { ...process.env, PGPASSWORD: decodeURIComponent(url.password) },
        encoding: 'utf8',
        maxBuffer: 64 * 1024 * 1024,
      },
    )
    if (res.error || res.status !== 0) throw new Error(res.error?.message ?? res.stderr)
    return res.stdout
  } finally {
    await sql`drop schema if exists ${sql.id(SCRATCH)} cascade`.execute(admin)
    await admin.destroy()
  }
}

function normalise(dumpText: string): string {
  const body = dumpText
    .split('\n')
    .filter((l) => !/^\\(un)?restrict /.test(l) && !/^-- (Dumped from|Dumped by|PostgreSQL database)/.test(l))
    .filter((l) => !new RegExp(`^CREATE SCHEMA ${SCRATCH};`).test(l))
    .join('\n')
    .replaceAll(`${SCRATCH}.`, 'public.')
    .replaceAll(SCRATCH, 'public')
    .replace(/\n{3,}/g, '\n\n')
  return `-- Generated by pnpm db:schema (migrations applied to an empty schema, pg_dump --schema-only). Do not edit; add a migration.\n${body}`
}

const next = normalise(await dump())
if (check) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : ''
  if (current !== next) {
    console.error('db/schema.sql is out of date; run `pnpm db:schema` and commit the result')
    process.exitCode = 1
  } else console.log('db:schema: up to date')
} else {
  writeFileSync(file, next)
  console.log(`wrote ${path.relative(process.cwd(), file)}`)
}
